-- Complete Problems Database Seed
-- Based on Blind 75, NeetCode 150, Grind 75, and curated DSA lists
-- Sources: https://neetcode.io, https://www.techinterviewhandbook.org/grind75/, https://leetcode.com

BEGIN;

-- Insert all problems with complete metadata
INSERT INTO problems (
  title, title_slug, difficulty, description,
  leetcode_id, topic_tags, acceptance_rate
) VALUES

-- ===== ARRAYS & HASHING =====
('Two Sum', 'two-sum', 'Easy',
'Given an array of integers nums and an integer target, return indices of the two numbers that add up to target.',
1, '["Array", "Hash Table"]'::jsonb, 49.1),

('Contains Duplicate', 'contains-duplicate', 'easy', 'arrays',
'Given an integer array nums, return true if any value appears at least twice.',
217, 'https://leetcode.com/problems/contains-duplicate/',
ARRAY['array', 'hash-table', 'sorting'],
ARRAY['Google', 'Amazon', 'Microsoft', 'Apple'],
'O(n)', 'O(n)', 60.8, 8500, 1100),

('Valid Anagram', 'valid-anagram', 'easy', 'strings',
'Given two strings s and t, return true if t is an anagram of s.',
242, 'https://leetcode.com/problems/valid-anagram/',
ARRAY['hash-table', 'string', 'sorting'],
ARRAY['Amazon', 'Bloomberg', 'Google', 'Microsoft'],
'O(n)', 'O(1)', 62.5, 9200, 300),

('Group Anagrams', 'group-anagrams', 'medium', 'strings',
'Given an array of strings, group the anagrams together.',
49, 'https://leetcode.com/problems/group-anagrams/',
ARRAY['array', 'hash-table', 'string', 'sorting'],
ARRAY['Amazon', 'Uber', 'Facebook', 'Google', 'Microsoft'],
'O(n*k log k)', 'O(n*k)', 65.9, 14000, 500),

('Top K Frequent Elements', 'top-k-frequent-elements', 'medium', 'arrays',
'Given an integer array nums and an integer k, return the k most frequent elements.',
347, 'https://leetcode.com/problems/top-k-frequent-elements/',
ARRAY['array', 'hash-table', 'heap', 'bucket-sort'],
ARRAY['Amazon', 'Facebook', 'Google', 'Microsoft', 'Apple'],
'O(n)', 'O(n)', 63.4, 12500, 600),

('Product of Array Except Self', 'product-of-array-except-self', 'medium', 'arrays',
'Return an array answer such that answer[i] is equal to the product of all elements except nums[i].',
238, 'https://leetcode.com/problems/product-of-array-except-self/',
ARRAY['array', 'prefix-sum'],
ARRAY['Amazon', 'Microsoft', 'Facebook', 'Apple', 'Google'],
'O(n)', 'O(1)', 64.2, 16500, 1200),

('Longest Consecutive Sequence', 'longest-consecutive-sequence', 'medium', 'arrays',
'Given an unsorted array of integers, find the length of the longest consecutive elements sequence.',
128, 'https://leetcode.com/problems/longest-consecutive-sequence/',
ARRAY['array', 'hash-table', 'union-find'],
ARRAY['Google', 'Amazon', 'Facebook', 'Microsoft'],
'O(n)', 'O(n)', 47.3, 14000, 600),

-- ===== TWO POINTERS =====
('Valid Palindrome', 'valid-palindrome', 'easy', 'strings',
'Given a string s, return true if it is a palindrome.',
125, 'https://leetcode.com/problems/valid-palindrome/',
ARRAY['two-pointers', 'string'],
ARRAY['Facebook', 'Microsoft', 'Amazon', 'Bloomberg'],
'O(n)', 'O(1)', 43.8, 6200, 6500),

('3Sum', '3sum', 'medium', 'arrays',
'Given an integer array nums, return all unique triplets that sum to zero.',
15, 'https://leetcode.com/problems/3sum/',
ARRAY['array', 'two-pointers', 'sorting'],
ARRAY['Amazon', 'Facebook', 'Google', 'Microsoft', 'Apple'],
'O(n²)', 'O(n)', 32.4, 23000, 2200),

('Container With Most Water', 'container-with-most-water', 'medium', 'arrays',
'Find two lines that together with the x-axis form a container that holds the most water.',
11, 'https://leetcode.com/problems/container-with-most-water/',
ARRAY['array', 'two-pointers', 'greedy'],
ARRAY['Amazon', 'Google', 'Facebook', 'Microsoft', 'Apple'],
'O(n)', 'O(1)', 54.1, 20500, 1100),

-- ===== SLIDING WINDOW =====
('Best Time to Buy and Sell Stock', 'best-time-to-buy-and-sell-stock', 'easy', 'arrays',
'Find the maximum profit by choosing a single day to buy and another to sell.',
121, 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',
ARRAY['array', 'dynamic-programming'],
ARRAY['Amazon', 'Microsoft', 'Facebook', 'Google', 'Apple'],
'O(n)', 'O(1)', 54.2, 20000, 700),

('Longest Substring Without Repeating Characters', 'longest-substring-without-repeating-characters', 'medium', 'strings',
'Find the length of the longest substring without repeating characters.',
3, 'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
ARRAY['hash-table', 'string', 'sliding-window'],
ARRAY['Amazon', 'Google', 'Facebook', 'Microsoft', 'Adobe'],
'O(n)', 'O(min(m,n))', 33.8, 31500, 1400),

('Longest Repeating Character Replacement', 'longest-repeating-character-replacement', 'medium', 'strings',
'Find the length of the longest substring containing the same letter after at most k changes.',
424, 'https://leetcode.com/problems/longest-repeating-character-replacement/',
ARRAY['hash-table', 'string', 'sliding-window'],
ARRAY['Amazon', 'Google', 'Microsoft'],
'O(n)', 'O(1)', 52.1, 6800, 250),

('Minimum Window Substring', 'minimum-window-substring', 'hard', 'strings',
'Find the minimum window substring of s that contains all characters of t.',
76, 'https://leetcode.com/problems/minimum-window-substring/',
ARRAY['hash-table', 'string', 'sliding-window'],
ARRAY['Amazon', 'Facebook', 'Google', 'Microsoft', 'Uber'],
'O(m+n)', 'O(m+n)', 39.7, 13500, 800),

-- ===== STACK =====
('Valid Parentheses', 'valid-parentheses', 'easy', 'strings',
'Determine if the input string of brackets is valid.',
20, 'https://leetcode.com/problems/valid-parentheses/',
ARRAY['string', 'stack'],
ARRAY['Amazon', 'Microsoft', 'Facebook', 'Google', 'Bloomberg'],
'O(n)', 'O(n)', 40.2, 17500, 1100),

-- ===== BINARY SEARCH =====
('Binary Search', 'binary-search', 'easy', 'arrays',
'Given a sorted array and target value, return the index or -1 if not found.',
704, 'https://leetcode.com/problems/binary-search/',
ARRAY['array', 'binary-search'],
ARRAY['Amazon', 'Google', 'Microsoft', 'Facebook'],
'O(log n)', 'O(1)', 55.3, 7500, 170),

('Search in Rotated Sorted Array', 'search-in-rotated-sorted-array', 'medium', 'arrays',
'Search for a target value in a rotated sorted array.',
33, 'https://leetcode.com/problems/search-in-rotated-sorted-array/',
ARRAY['array', 'binary-search'],
ARRAY['Amazon', 'Facebook', 'Microsoft', 'Google', 'Apple'],
'O(log n)', 'O(1)', 38.9, 18500, 1100),

('Find Minimum in Rotated Sorted Array', 'find-minimum-in-rotated-sorted-array', 'medium', 'arrays',
'Find the minimum element in a rotated sorted array.',
153, 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/',
ARRAY['array', 'binary-search'],
ARRAY['Amazon', 'Microsoft', 'Google', 'Facebook'],
'O(log n)', 'O(1)', 49.2, 9400, 430),

-- ===== LINKED LIST =====
('Reverse Linked List', 'reverse-linked-list', 'easy', 'linked-list',
'Reverse a singly linked list.',
206, 'https://leetcode.com/problems/reverse-linked-list/',
ARRAY['linked-list', 'recursion'],
ARRAY['Amazon', 'Microsoft', 'Facebook', 'Google', 'Apple'],
'O(n)', 'O(1)', 72.1, 16500, 310),

('Merge Two Sorted Lists', 'merge-two-sorted-lists', 'easy', 'linked-list',
'Merge two sorted linked lists into one sorted list.',
21, 'https://leetcode.com/problems/merge-two-sorted-lists/',
ARRAY['linked-list', 'recursion'],
ARRAY['Amazon', 'Microsoft', 'Google', 'Facebook', 'Apple'],
'O(n+m)', 'O(1)', 61.5, 16000, 1200),

('Linked List Cycle', 'linked-list-cycle', 'easy', 'linked-list',
'Determine if a linked list has a cycle.',
141, 'https://leetcode.com/problems/linked-list-cycle/',
ARRAY['hash-table', 'linked-list', 'two-pointers'],
ARRAY['Amazon', 'Microsoft', 'Facebook', 'Google'],
'O(n)', 'O(1)', 47.1, 11500, 800),

('Reorder List', 'reorder-list', 'medium', 'linked-list',
'Reorder list nodes in L0→Ln→L1→Ln-1→L2→Ln-2→… pattern.',
143, 'https://leetcode.com/problems/reorder-list/',
ARRAY['linked-list', 'two-pointers', 'stack'],
ARRAY['Amazon', 'Microsoft', 'Facebook'],
'O(n)', 'O(1)', 51.3, 8100, 280),

('Remove Nth Node From End of List', 'remove-nth-node-from-end-of-list', 'medium', 'linked-list',
'Remove the nth node from the end of a linked list.',
19, 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/',
ARRAY['linked-list', 'two-pointers'],
ARRAY['Amazon', 'Microsoft', 'Google', 'Facebook'],
'O(n)', 'O(1)', 40.5, 14500, 650),

('Merge K Sorted Lists', 'merge-k-sorted-lists', 'hard', 'linked-list',
'Merge k sorted linked lists into one sorted list.',
23, 'https://leetcode.com/problems/merge-k-sorted-lists/',
ARRAY['linked-list', 'divide-and-conquer', 'heap', 'merge-sort'],
ARRAY['Amazon', 'Facebook', 'Google', 'Microsoft', 'Apple'],
'O(N log k)', 'O(k)', 48.7, 14000, 550),

-- ===== TREES =====
('Invert Binary Tree', 'invert-binary-tree', 'easy', 'tree',
'Invert a binary tree (swap left and right children).',
226, 'https://leetcode.com/problems/invert-binary-tree/',
ARRAY['tree', 'depth-first-search', 'breadth-first-search'],
ARRAY['Google', 'Amazon', 'Facebook', 'Microsoft'],
'O(n)', 'O(h)', 73.5, 10800, 170),

('Maximum Depth of Binary Tree', 'maximum-depth-of-binary-tree', 'easy', 'tree',
'Find the maximum depth of a binary tree.',
104, 'https://leetcode.com/problems/maximum-depth-of-binary-tree/',
ARRAY['tree', 'depth-first-search', 'breadth-first-search'],
ARRAY['Amazon', 'Microsoft', 'Facebook', 'Google'],
'O(n)', 'O(h)', 72.8, 9500, 180),

('Same Tree', 'same-tree', 'easy', 'tree',
'Determine if two binary trees are identical.',
100, 'https://leetcode.com/problems/same-tree/',
ARRAY['tree', 'depth-first-search', 'breadth-first-search'],
ARRAY['Amazon', 'Google', 'Microsoft'],
'O(n)', 'O(h)', 57.2, 8600, 180),

('Subtree of Another Tree', 'subtree-of-another-tree', 'easy', 'tree',
'Check if subRoot is a subtree of root.',
572, 'https://leetcode.com/problems/subtree-of-another-tree/',
ARRAY['tree', 'depth-first-search', 'string-matching'],
ARRAY['Amazon', 'Facebook', 'Microsoft', 'Google'],
'O(m*n)', 'O(h)', 46.8, 6700, 340),

('Lowest Common Ancestor of a Binary Search Tree', 'lowest-common-ancestor-of-a-binary-search-tree', 'medium', 'tree',
'Find the lowest common ancestor of two nodes in a BST.',
235, 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/',
ARRAY['tree', 'depth-first-search', 'binary-search-tree'],
ARRAY['Amazon', 'Facebook', 'Microsoft', 'Google'],
'O(h)', 'O(h)', 62.1, 8900, 260),

('Binary Tree Level Order Traversal', 'binary-tree-level-order-traversal', 'medium', 'tree',
'Return the level order traversal of a binary tree.',
102, 'https://leetcode.com/problems/binary-tree-level-order-traversal/',
ARRAY['tree', 'breadth-first-search'],
ARRAY['Amazon', 'Microsoft', 'Facebook', 'Google', 'Bloomberg'],
'O(n)', 'O(n)', 62.3, 12000, 260),

('Validate Binary Search Tree', 'validate-binary-search-tree', 'medium', 'tree',
'Determine if a binary tree is a valid BST.',
98, 'https://leetcode.com/problems/validate-binary-search-tree/',
ARRAY['tree', 'depth-first-search', 'binary-search-tree'],
ARRAY['Amazon', 'Facebook', 'Microsoft', 'Google', 'Bloomberg'],
'O(n)', 'O(h)', 31.6, 13500, 1100),

('Kth Smallest Element in a BST', 'kth-smallest-element-in-a-bst', 'medium', 'tree',
'Find the kth smallest element in a BST.',
230, 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/',
ARRAY['tree', 'depth-first-search', 'binary-search-tree'],
ARRAY['Amazon', 'Google', 'Facebook', 'Microsoft'],
'O(h+k)', 'O(h)', 68.5, 9200, 180),

('Construct Binary Tree from Preorder and Inorder Traversal', 'construct-binary-tree-from-preorder-and-inorder-traversal', 'medium', 'tree',
'Build a binary tree from preorder and inorder traversals.',
105, 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/',
ARRAY['array', 'hash-table', 'divide-and-conquer', 'tree'],
ARRAY['Amazon', 'Microsoft', 'Facebook', 'Google'],
'O(n)', 'O(n)', 59.5, 11500, 340),

('Binary Tree Maximum Path Sum', 'binary-tree-maximum-path-sum', 'hard', 'tree',
'Find the maximum path sum in a binary tree.',
124, 'https://leetcode.com/problems/binary-tree-maximum-path-sum/',
ARRAY['dynamic-programming', 'tree', 'depth-first-search'],
ARRAY['Amazon', 'Facebook', 'Microsoft', 'Google', 'Apple'],
'O(n)', 'O(h)', 37.9, 13000, 680),

('Serialize and Deserialize Binary Tree', 'serialize-and-deserialize-binary-tree', 'hard', 'tree',
'Design an algorithm to serialize and deserialize a binary tree.',
297, 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/',
ARRAY['string', 'tree', 'depth-first-search', 'breadth-first-search', 'design'],
ARRAY['Amazon', 'Microsoft', 'Google', 'Facebook', 'Bloomberg'],
'O(n)', 'O(n)', 54.2, 9700, 380),

-- ===== TRIES =====
('Implement Trie (Prefix Tree)', 'implement-trie-prefix-tree', 'medium', 'trie',
'Implement a trie with insert, search, and startsWith operations.',
208, 'https://leetcode.com/problems/implement-trie-prefix-tree/',
ARRAY['hash-table', 'string', 'design', 'trie'],
ARRAY['Amazon', 'Microsoft', 'Google', 'Facebook', 'Bloomberg'],
'O(m)', 'O(n*m)', 60.2, 9800, 160),

('Design Add and Search Words Data Structure', 'design-add-and-search-words-data-structure', 'medium', 'trie',
'Design a data structure that supports adding words and searching with wildcards.',
211, 'https://leetcode.com/problems/design-add-and-search-words-data-structure/',
ARRAY['string', 'depth-first-search', 'design', 'trie'],
ARRAY['Amazon', 'Facebook', 'Google', 'Microsoft'],
'O(m)', 'O(n*m)', 45.7, 6500, 410),

('Word Search II', 'word-search-ii', 'hard', 'trie',
'Find all words in a 2D board that exist in a dictionary.',
212, 'https://leetcode.com/problems/word-search-ii/',
ARRAY['array', 'string', 'backtracking', 'trie', 'matrix'],
ARRAY['Amazon', 'Microsoft', 'Google', 'Facebook', 'Apple'],
'O(m*n*4^L)', 'O(k*L)', 38.1, 8500, 420),

-- ===== HEAP / PRIORITY QUEUE =====
('Find Median from Data Stream', 'find-median-from-data-stream', 'hard', 'heap',
'Design a data structure that supports adding numbers and finding the median.',
295, 'https://leetcode.com/problems/find-median-from-data-stream/',
ARRAY['two-pointers', 'design', 'sorting', 'heap', 'data-stream'],
ARRAY['Amazon', 'Google', 'Facebook', 'Microsoft', 'Apple'],
'O(log n)', 'O(n)', 51.1, 9200, 230),

-- ===== BACKTRACKING =====
('Combination Sum', 'combination-sum', 'medium', 'backtracking',
'Find all unique combinations in candidates that sum to target.',
39, 'https://leetcode.com/problems/combination-sum/',
ARRAY['array', 'backtracking'],
ARRAY['Amazon', 'Microsoft', 'Facebook', 'Google', 'Uber'],
'O(2^n)', 'O(target/min)', 68.6, 14500, 320),

('Word Search', 'word-search', 'medium', 'backtracking',
'Determine if a word exists in a 2D board.',
79, 'https://leetcode.com/problems/word-search/',
ARRAY['array', 'backtracking', 'matrix'],
ARRAY['Amazon', 'Microsoft', 'Facebook', 'Google', 'Bloomberg'],
'O(m*n*4^L)', 'O(L)', 40.1, 11500, 440),

-- ===== GRAPHS =====
('Number of Islands', 'number-of-islands', 'medium', 'graph',
'Count the number of islands in a 2D grid.',
200, 'https://leetcode.com/problems/number-of-islands/',
ARRAY['array', 'depth-first-search', 'breadth-first-search', 'union-find', 'matrix'],
ARRAY['Amazon', 'Facebook', 'Microsoft', 'Google', 'Bloomberg'],
'O(m*n)', 'O(m*n)', 56.7, 18000, 420),

('Clone Graph', 'clone-graph', 'medium', 'graph',
'Return a deep copy of a connected undirected graph.',
133, 'https://leetcode.com/problems/clone-graph/',
ARRAY['hash-table', 'depth-first-search', 'breadth-first-search', 'graph'],
ARRAY['Amazon', 'Facebook', 'Google', 'Microsoft'],
'O(N+M)', 'O(N)', 50.3, 7800, 2600),

('Pacific Atlantic Water Flow', 'pacific-atlantic-water-flow', 'medium', 'graph',
'Find cells that can flow to both Pacific and Atlantic oceans.',
417, 'https://leetcode.com/problems/pacific-atlantic-water-flow/',
ARRAY['array', 'depth-first-search', 'breadth-first-search', 'matrix'],
ARRAY['Amazon', 'Google', 'Facebook', 'Microsoft'],
'O(m*n)', 'O(m*n)', 52.8, 6200, 970),

('Course Schedule', 'course-schedule', 'medium', 'graph',
'Determine if you can finish all courses given prerequisites.',
207, 'https://leetcode.com/problems/course-schedule/',
ARRAY['depth-first-search', 'breadth-first-search', 'graph', 'topological-sort'],
ARRAY['Amazon', 'Microsoft', 'Facebook', 'Google', 'Bloomberg'],
'O(V+E)', 'O(V+E)', 45.3, 12000, 480),

('Course Schedule II', 'course-schedule-ii', 'medium', 'graph',
'Return the ordering of courses you should take.',
210, 'https://leetcode.com/problems/course-schedule-ii/',
ARRAY['depth-first-search', 'breadth-first-search', 'graph', 'topological-sort'],
ARRAY['Amazon', 'Facebook', 'Microsoft', 'Google'],
'O(V+E)', 'O(V+E)', 48.2, 9200, 320),

-- ===== DYNAMIC PROGRAMMING =====
('Climbing Stairs', 'climbing-stairs', 'easy', 'dynamic-programming',
'Count the number of ways to climb n stairs taking 1 or 2 steps.',
70, 'https://leetcode.com/problems/climbing-stairs/',
ARRAY['math', 'dynamic-programming', 'memoization'],
ARRAY['Amazon', 'Microsoft', 'Google', 'Facebook', 'Apple'],
'O(n)', 'O(1)', 51.4, 16500, 520),

('House Robber', 'house-robber', 'medium', 'dynamic-programming',
'Rob houses without robbing two adjacent houses.',
198, 'https://leetcode.com/problems/house-robber/',
ARRAY['array', 'dynamic-programming'],
ARRAY['Amazon', 'Google', 'Microsoft', 'Facebook'],
'O(n)', 'O(1)', 48.5, 16000, 360),

('House Robber II', 'house-robber-ii', 'medium', 'dynamic-programming',
'Rob houses arranged in a circle without robbing adjacent houses.',
213, 'https://leetcode.com/problems/house-robber-ii/',
ARRAY['array', 'dynamic-programming'],
ARRAY['Amazon', 'Microsoft', 'Google', 'Facebook'],
'O(n)', 'O(1)', 40.5, 7600, 130),

('Longest Palindromic Substring', 'longest-palindromic-substring', 'medium', 'dynamic-programming',
'Find the longest palindromic substring in s.',
5, 'https://leetcode.com/problems/longest-palindromic-substring/',
ARRAY['string', 'dynamic-programming'],
ARRAY['Amazon', 'Microsoft', 'Facebook', 'Google', 'Adobe'],
'O(n²)', 'O(n²)', 32.4, 23500, 1400),

('Palindromic Substrings', 'palindromic-substrings', 'medium', 'dynamic-programming',
'Count how many palindromic substrings are in the string.',
647, 'https://leetcode.com/problems/palindromic-substrings/',
ARRAY['string', 'dynamic-programming'],
ARRAY['Amazon', 'Facebook', 'Microsoft', 'Google'],
'O(n²)', 'O(1)', 66.5, 8800, 210),

('Decode Ways', 'decode-ways', 'medium', 'dynamic-programming',
'Count the number of ways to decode a string of digits.',
91, 'https://leetcode.com/problems/decode-ways/',
ARRAY['string', 'dynamic-programming'],
ARRAY['Amazon', 'Facebook', 'Google', 'Microsoft', 'Uber'],
'O(n)', 'O(1)', 32.1, 9400, 4100),

('Coin Change', 'coin-change', 'medium', 'dynamic-programming',
'Find the minimum number of coins needed to make up an amount.',
322, 'https://leetcode.com/problems/coin-change/',
ARRAY['array', 'dynamic-programming', 'breadth-first-search'],
ARRAY['Amazon', 'Microsoft', 'Google', 'Facebook', 'Apple'],
'O(amount*n)', 'O(amount)', 42.1, 15000, 380),

('Maximum Product Subarray', 'maximum-product-subarray', 'medium', 'dynamic-programming',
'Find the contiguous subarray with the largest product.',
152, 'https://leetcode.com/problems/maximum-product-subarray/',
ARRAY['array', 'dynamic-programming'],
ARRAY['Amazon', 'Microsoft', 'Google', 'Facebook', 'LinkedIn'],
'O(n)', 'O(1)', 34.6, 13500, 430),

('Word Break', 'word-break', 'medium', 'dynamic-programming',
'Determine if string can be segmented into dictionary words.',
139, 'https://leetcode.com/problems/word-break/',
ARRAY['hash-table', 'string', 'dynamic-programming', 'trie'],
ARRAY['Amazon', 'Microsoft', 'Facebook', 'Google', 'Bloomberg'],
'O(n*m*k)', 'O(n)', 45.1, 13000, 600),

('Longest Increasing Subsequence', 'longest-increasing-subsequence', 'medium', 'dynamic-programming',
'Find the length of the longest strictly increasing subsequence.',
300, 'https://leetcode.com/problems/longest-increasing-subsequence/',
ARRAY['array', 'binary-search', 'dynamic-programming'],
ARRAY['Amazon', 'Microsoft', 'Google', 'Facebook'],
'O(n log n)', 'O(n)', 51.7, 15000, 290),

('Unique Paths', 'unique-paths', 'medium', 'dynamic-programming',
'Count unique paths from top-left to bottom-right in a grid.',
62, 'https://leetcode.com/problems/unique-paths/',
ARRAY['math', 'dynamic-programming', 'combinatorics'],
ARRAY['Amazon', 'Google', 'Facebook', 'Microsoft', 'Bloomberg'],
'O(m*n)', 'O(n)', 63.2, 12500, 300),

('Jump Game', 'jump-game', 'medium', 'dynamic-programming',
'Determine if you can reach the last index.',
55, 'https://leetcode.com/problems/jump-game/',
ARRAY['array', 'dynamic-programming', 'greedy'],
ARRAY['Amazon', 'Microsoft', 'Google', 'Facebook', 'Bloomberg'],
'O(n)', 'O(1)', 38.4, 14500, 720),

-- ===== GREEDY =====
('Maximum Subarray', 'maximum-subarray', 'medium', 'arrays',
'Find the contiguous subarray with the largest sum.',
53, 'https://leetcode.com/problems/maximum-subarray/',
ARRAY['array', 'divide-and-conquer', 'dynamic-programming'],
ARRAY['Amazon', 'Microsoft', 'Google', 'Facebook', 'Bloomberg'],
'O(n)', 'O(1)', 50.0, 27000, 1200),

-- ===== INTERVALS =====
('Insert Interval', 'insert-interval', 'medium', 'intervals',
'Insert a new interval and merge if necessary.',
57, 'https://leetcode.com/problems/insert-interval/',
ARRAY['array'],
ARRAY['Amazon', 'Google', 'Facebook', 'Microsoft', 'Bloomberg'],
'O(n)', 'O(n)', 38.7, 7600, 530),

('Merge Intervals', 'merge-intervals', 'medium', 'intervals',
'Merge all overlapping intervals.',
56, 'https://leetcode.com/problems/merge-intervals/',
ARRAY['array', 'sorting'],
ARRAY['Amazon', 'Microsoft', 'Facebook', 'Google', 'Bloomberg'],
'O(n log n)', 'O(n)', 45.9, 17000, 640),

('Non-overlapping Intervals', 'non-overlapping-intervals', 'medium', 'intervals',
'Find minimum number of intervals to remove to make rest non-overlapping.',
435, 'https://leetcode.com/problems/non-overlapping-intervals/',
ARRAY['array', 'dynamic-programming', 'greedy', 'sorting'],
ARRAY['Amazon', 'Microsoft', 'Facebook', 'Google'],
'O(n log n)', 'O(1)', 50.3, 6200, 160),

-- ===== BIT MANIPULATION =====
('Number of 1 Bits', 'number-of-1-bits', 'easy', 'bit-manipulation',
'Count the number of 1 bits in an unsigned integer.',
191, 'https://leetcode.com/problems/number-of-1-bits/',
ARRAY['divide-and-conquer', 'bit-manipulation'],
ARRAY['Amazon', 'Microsoft', 'Google', 'Facebook'],
'O(1)', 'O(1)', 65.3, 4200, 1100),

('Counting Bits', 'counting-bits', 'easy', 'bit-manipulation',
'Return an array where ans[i] is the number of 1 bits in i.',
338, 'https://leetcode.com/problems/counting-bits/',
ARRAY['dynamic-programming', 'bit-manipulation'],
ARRAY['Amazon', 'Google', 'Microsoft', 'Facebook'],
'O(n)', 'O(n)', 75.1, 9100, 420),

('Reverse Bits', 'reverse-bits', 'easy', 'bit-manipulation',
'Reverse bits of a 32-bit unsigned integer.',
190, 'https://leetcode.com/problems/reverse-bits/',
ARRAY['divide-and-conquer', 'bit-manipulation'],
ARRAY['Amazon', 'Facebook', 'Microsoft', 'Apple'],
'O(1)', 'O(1)', 51.7, 4400, 1200),

('Missing Number', 'missing-number', 'easy', 'bit-manipulation',
'Find the missing number from 0 to n.',
268, 'https://leetcode.com/problems/missing-number/',
ARRAY['array', 'hash-table', 'math', 'binary-search', 'bit-manipulation', 'sorting'],
ARRAY['Amazon', 'Microsoft', 'Google', 'Facebook'],
'O(n)', 'O(1)', 61.2, 9500, 3100),

('Sum of Two Integers', 'sum-of-two-integers', 'medium', 'bit-manipulation',
'Calculate sum of two integers without using + or - operators.',
371, 'https://leetcode.com/problems/sum-of-two-integers/',
ARRAY['math', 'bit-manipulation'],
ARRAY['Amazon', 'Microsoft', 'Google'],
'O(1)', 'O(1)', 51.0, 3400, 4400);

COMMIT;
