declare module 'lucide-react' {
  import { FC, SVGProps } from 'react';

  export interface IconProps extends SVGProps<SVGSVGElement> {
    size?: number | string;
    strokeWidth?: number | string;
    absoluteStrokeWidth?: boolean;
  }

  export type Icon = FC<IconProps>;

  export const ArrowRightIcon: Icon;
  export const Calendar: Icon;
  export const ChevronLeft: Icon;
  export const ChevronRight: Icon;
  export const ChevronDown: Icon;
  export const Video: Icon;
  export const VideoOff: Icon;
  export const Users: Icon;
  export const Clock: Icon;
  export const Code: Icon;
  export const Code2: Icon;
  export const Trophy: Icon;
  export const Target: Icon;
  export const Sparkles: Icon;
  export const TrendingUp: Icon;
  export const CheckCircle2: Icon;
  export const X: Icon;
  export const Plus: Icon;
  export const MoreVertical: Icon;
  export const User: Icon;
  export const Settings: Icon;
  export const LogOut: Icon;
  export const BarChart3: Icon;
  export const Bell: Icon;
  export const Flame: Icon;
  export const Star: Icon;
  export const Award: Icon;
  export const BookOpen: Icon;
  export const Share2: Icon;
  export const MapPin: Icon;
  export const Briefcase: Icon;
  export const GraduationCap: Icon;
  export const Github: Icon;
  export const Linkedin: Icon;
  export const Globe: Icon;
  export const Play: Icon;
  export const Send: Icon;
  export const RotateCcw: Icon;
  export const Loader2: Icon;
  export const Mic: Icon;
  export const MicOff: Icon;
  export const PhoneOff: Icon;
  export const Monitor: Icon;
  export const MonitorUp: Icon;
  export const MonitorOff: Icon;
  export const MessageSquare: Icon;
  export const Terminal: Icon;
  export const FileCode: Icon;
  export const Copy: Icon;
  export const Check: Icon;
  export const PanelLeftClose: Icon;
  export const PanelLeft: Icon;
  export const Crown: Icon;
  export const Wifi: Icon;
  export const WifiOff: Icon;
  export const Circle: Icon;
  export const Separator: Icon;
  export const Pencil: Icon;
  export const PenLine: Icon;
  export const Edit: Icon;
  export const Zap: Icon;
  export const MoreHorizontal: Icon;
  export const Maximize2: Icon;
  export const Minimize2: Icon;
  export const Eraser: Icon;
  export const Trash2: Icon;
  export const Palette: Icon;
  export const PenTool: Icon;
  export const Layout: Icon;
  export const Grid3X3: Icon;
  export const ArrowLeft: Icon;
  export const MousePointer2: Icon;
  export const Hand: Icon;
  export const Square: Icon;
  export const CircleIcon: Icon;
  export const Minus: Icon;
  export const ArrowUpRight: Icon;
  export const Type: Icon;
  export const Undo2: Icon;
  export const Redo2: Icon;
  export const ZoomIn: Icon;
  export const ZoomOut: Icon;
}
